CREATE SEQUENCE SQ_TBL_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USUARIO (
    USUARIO_ID INTEGER DEFAULT SQ_T_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(10) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);
